SELECT PRODUCT_CODE, SUM(PRICE * OFFLINE_SALE.SALES_AMOUNT) AS SALES
FROM PRODUCT
INNER JOIN OFFLINE_SALE
    ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;