SELECT ICECREAM_INFO.INGREDIENT_TYPE, SUM(TOTAL_ORDER)
FROM FIRST_HALF
INNER JOIN ICECREAM_INFO
    ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
GROUP BY ICECREAM_INFO.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;